---
- name: "Restart dnsdist"
  systemd:
    daemon_reload: "yes"
    name:          "{{ item.name }}"
    state:         "restarted"
  with_items: "{{ configure_dnsdist.services[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | default([]) }}"
  listen: "dnsdist-restart"
